name: IndexNow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Mega step
        uses: actions/github-script@v6
        with:
          script: |
            require("fast-xml-parser");
            import { XMLParser } from "fast-xml-parser";
            const parser = new XMLParser();
            var file;
            fetch("https://vitaliklevin.github.io/sitemap.xml")
              .then((res) => { return res.blob() })
              .then((blob) => {
                file = parser.parse(blob);
                for(url in file.urlset) {
                  fetch(`https://yandex.com/indexnow?url=${url.loc}&key=68537cd552ad4fc992f52fd5685725b2`)
                }
              })